baseURL = 'https://nkoorty.github.io/'
languageCode = 'en-us'
title = 'Nkoorty'
theme = 'PaperMod'

[params]
  [params.homeInfoParams]
    Title = "Artemiy Malyshau"
    Content = "Hi, this website acts as an 'extended' CV or portfolio. I'm an MSc student and scholar at Imperial College London studying Applied Computational Science and Engineering. My research interests lie in (multi-agent) reinforcement learning and iOS development. I also really like attending hackathons."

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/nkoorty"

  [[params.socialIcons]]
    name = "twitter"
    url = "https://twitter.com/nkoorty"

  [[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/artemiy-malyshau/"

[menu]

  [[menu.main]]
    identifier = "experience"
    name = "Experience"
    url = "/experience"
    weight = 1

  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    weight = 2

  [[menu.main]]
    identifier = "hackathons"
    name = "Hackathons"
    url = "/hackathons/"
    weight = 3

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 4