baseURL = 'https://nkoorty.github.io/'
languageCode = 'en-us'
title = 'Nkoorty'
theme = 'PaperMod'

[params]
  [params.homeInfoParams]
    Title = "Artemiy Malyshau"
    Content = "Test"

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/nkoorty"

  [[params.socialIcons]]
    name = "twitter"
    url = "https://twitter.com/nkoorty"

  [[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/artemiy-malyshau/"

[menu]

  [[menu.main]]
    identifier = "experience"
    name = "Experience"
    url = "/experience"
    weight = 1

  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    weight = 2

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 3